spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    student:
      jdbc-url: jdbc:postgresql://localhost:5433/student_database
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
